### ISSUE TITLE
Mismatch in Timestamps Between ossec.log on Server and Web Interface

### ISSUE THREAD

**Issue by sakib789** [wazuh/wazuh-dashboard-plugins#6563]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | - | Manager | - | Ubuntu22.04 |

Dear Team,

While working with this [community](https://github.com/wazuh/community/issues/22117), I've observed a notable time variance between the timestamps recorded in the ossec.log on the server and those displayed in the web interface for the same log.

Firstly, when accessing the ossec.log directly on the server at `/var/ossec/log/ossec.log`, I'm able to view the logs in real-time, as depicted in the accompanying image.
![image](https://github.com/wazuh/wazuh/assets/67746422/e87c1a5e-2b9e-4279-917a-84e3306818c8)

Furthermore, I've also explored accessing logs in real-time via API requests from both the server and the web interface(API Console), as illustrated in the provided images.
![image](https://github.com/wazuh/wazuh/assets/67746422/661069f9-fa73-4c82-86e8-de279d295175)
![image](https://github.com/wazuh/wazuh/assets/67746422/9eb6bbc3-1b94-4538-88bb-dfc99cc4d06c)

My Wazuh server is configured to record logs in local time.
![image](https://github.com/wazuh/wazuh/assets/67746422/4fee2540-6781-47d4-bc3a-e20d4ff133d1)

Despite my attempts to align the time settings on the web interface with both browser time and local time, I consistently encounter a discrepancy where the timestamps displayed for ossec.log in the web interface appear to be ahead of my local time, regardless of whether it's in UTC or local time.
![image](https://github.com/wazuh/wazuh/assets/67746422/0e2205fe-e862-4d6e-9d64-eae80285af44)

I kindly request your assistance in investigating and sharing your insights into this matter.

**Comment by sakib789** [comment]
It seems the issue is resolved in the latest version(4.8.1) 
![image](https://github.com/user-attachments/assets/823cb47e-71cb-467f-8af3-29c71dbf77a6)

**Comment by Antyrael** [comment]
I am running Wazuh Manager v4.8.2 and my agents are also v4.8.2, but I'm still seeing the timestamp discrepancy.

![dashboard_logs](https://github.com/user-attachments/assets/9957670b-b0f4-4384-a618-5cb59e2c18a5)
![ossec_log](https://github.com/user-attachments/assets/dbca19f2-26b0-4271-aa1e-c41d38608276)

The timestamps shown on the dashboard are 2 hours in the future:
![image_2024-09-02_113318344](https://github.com/user-attachments/assets/b7d5ff47-7104-47d4-ac9b-2b28ed63c539)

@sakib789 did you do anything else to get these timestamps the same?

**Comment by Desvelao** [comment]
Hi @sakib789 and @Antyrael , the displayed log timestamp is not the raw text you can find in `/var/ossec/logs/ossec.log`, this is formatted taking into account:
- date returned by the Wazuh API response
> Assuming this is set in UTC (+0). If this returns a local timestamp I am not sure if could cause a bug.
- configuration of Wazuh dashboard:
  - format: `dateFormat` setting on Advanced settings of Wazuh dashboard
  - timezone: `dateFormat:tz` setting on Advanced settings of Wazuh dashboard

Due to the settings configuration on the Wazuh dashboard, the displayed timestamp of the Wazuh server log could have a difference related to the timezone.
> Note the date format is different too (by default)

For example, the timestamp is formatted here for 4.8.1: https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.8.1-2.10.0/plugins/main/public/controllers/management/components/management/mg-logs/logs.js#L151

**Comment by Desvelao** [comment]
I will close the issue because this is the expected behavior.

Feel free to reopen the issue for any related questions or problems encountered.

**Comment by Antyrael** [comment]
Thanks for the explanation @Desvelao.
After changing the timezone setting to ETC/Universal on the Advanced settings of Wazuh Dashboard, the logs now show the correct time for me.

I hope adding this comment does not reopen this issue, but I at least wanted to share my appreciation and result of your explanation.
